import { signIn, signOut, useSession } from 'next-auth/client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Button } from '@chakra-ui/button';
import { Link } from "@chakra-ui/react"


const Home = () => {
  const [session, loading] = useSession();

  // Don't need token in localStorage, it sits in cookies
  // if (session && session.accessToken && localStorage.getItem('token') !== session.accessToken) {
  //   localStorage.setItem('token', session.accessToken as string);
  // }
  
  if (!session) {
    return (
      <div className={styles.container}>
        <main>
          <p>Not signed in</p>
          <Button onClick={() => signIn()}>Sign in</Button>
        </main>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Button onClick={() => signOut()}>Sign out</Button>
        <h1>Hello</h1>
        <Button background="green.200"><Link href="/app">Go to dashboard</Link></Button>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
