import { signIn, signOut, useSession } from 'next-auth/client';
import Head from 'next/head';


const Home = () => {
  const [session, loading] = useSession();

  // Don't need token in localStorage, it sits in cookies
  // if (session && session.accessToken && localStorage.getItem('token') !== session.accessToken) {
  //   localStorage.setItem('token', session.accessToken as string);
  // }
  
  if (!session) {
    return (
      <div>
        <main>
          <p>Not signed in</p>
          <button onClick={() => signIn()}>Sign in</button>
        </main>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Kennel App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <button onClick={() => signOut()}>Sign out</button>
        <h1>Hello</h1>
        <button className="bg-green-200"><a href="/app">Go to dashboard</a></button>
      </main>
    </div>
  );
};

export default Home;
